# Generated by Django 6.0 on 2025-12-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='persone',
            name='name',
            field=models.CharField(max_length=50, verbose_name='ФИО сотрудника'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Вн. номер'),
        ),
    ]
